name: Single Bot Runner

on:
  schedule:
    - cron: "0 */3 * * *"  # هر ۳ ساعت یک بار در دقیقه صفر
  workflow_dispatch:        # برای اجرای دستی

concurrency:
  group: single-bot-runner
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: نصب کتابخانه‌ها
        run: pip install -r requirements.txt

      - name: اجرای ربات
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
        run: python bot.py
